### ISSUE TITLE
Episode: sound

### ISSUE THREAD

**Issue by samumantha** [coderefinery/train-the-trainer#81]
For old/other materials, see #80

**Comment by rkdarst** [comment]
Three take-away points:

- Audio is far more important than video (almost as important as good screenshare).
- Have a wired headset with mouthpiece, or one with a dedicated dongle.  Bluetooth has too much latency for interactive work.
- Test in advance:  Get someone to listen and comment.  Check how to do your mic volume adjustment can go from very low to very high, so that you can adjust to the needs.

All I know is currently here (could this be the lesson material?): https://coderefinery.github.io/manuals/instructor-tech-online/#audio

**Comment by samumantha** [comment]
About the manuals vs lesson material: Radovan also mentioned this in some other issue earlier; we could have at least a summary and exercises in lecture materials, but can link to more in-depth material in manuals, if it exists. What do you think?

**Comment by bast** [comment]
Referring to manuals is good but I try to create a learning material which does not require too much navigation to other pages which may contain a lot more. But we also don't want too much duplication. Trying to find a good balance there.
