### ISSUE TITLE
Episode: lesson development

### ISSUE THREAD

**Issue by samumantha** [coderefinery/train-the-trainer#84]
Available old/other materials on the topic:
- https://coderefinery.github.io/train-the-trainer/branch/community-teaching/lessons-with-version-control/
- https://coderefinery.github.io/train-the-trainer/branch/community-teaching/backward-lesson-design/
- https://coderefinery.github.io/train-the-trainer/branch/instructor-training/lesson-development/
- https://coderefinery.github.io/manuals/lesson-design/
- https://coderefinery.github.io/manuals/lesson-review/

You do not need to reuse anything, but can :)

**Comment by samumantha** [comment]
Please also include an overview of our available lesson materials :)

**Comment by rantahar** [comment]
Draft for lesson development session added (PR #103)

I want to say a bit more about exercises and assessments, but I still need to think a bit first.

**Comment by samumantha** [comment]
Coordinator note: Draft in lesson materials ✔️

**Comment by bast** [comment]
Notes from meeting today:
- start with notes exercise: how do you design lessons?
- later 20 min exercise where we list some topics and don't require participants to browse our lessons
- discuss how we design lessons with use case git lesson and show how it evolved over time

**Comment by bast** [comment]
Some follow-up moved to #117.

**Comment by rkdarst** [comment]
Comments on lesson development episode:

It's good.  Not much more to do, it will be a good discussion.  My thoughts:

- CodeRefinery lessons seem simpler than most: do you think this is good or not.  That's because we do this process and need to be accessible to many people.
- I always think of the learning objectives as "three simple enough messages that someone will remember the next day. (not highly technical topics)"  They need to be pretty simple.
- I like the exercise.  Emphasize that the goal is to make it simple, not complex, and it's actually hard to come up with simple enough messages/exercises for a wide audience to be able to.

A lot of these can be voice discussion to go with the material rather than more text.

+1 to the other issue about talking about the history and how it is more and more simplified *because that's what people need*

**Comment by bast** [comment]
Thanks! I will work on those and close once they are implemented.

**Comment by samumantha** [comment]
Note: improving existing lessons mentions to create "issues". In the current setup we will not have mentioned that we keep our materials on GitHub before that point. Or maybe we do? (but its not in material)
Suggestion to solve: Move browsing our lessons and talking about source and on GitHub to above "improving existing lessons"? 
Discussing the version control episode could stay in the grey box where it is now?

**Comment by bast** [comment]
Thanks to both of you for feedback - this is now implemented.
