### ISSUE TITLE
Episode: lessons with version control (lesson template)

### ISSUE THREAD

**Issue by samumantha** [coderefinery/train-the-trainer#85]
Available old/other materials on the topic:
- https://github.com/coderefinery/sphinx-lesson-template

**Comment by rkdarst** [comment]
This is the first of all episodes, so it's also an introduction to many things.

Should this possibly be after "lesson development" which goes into the basics of why we use git as a lesson design (regardless of the template).  Then we can talk only about what is special about our template.

Proposed "take-away" messages, if this became the second lesson:
- sphinx-lesson isn't anything really new: it's "just Sphinx", a normal tool that many use
- The addition is various directives (boxes) tuned to lesson purposes
- In addition it provides a sample organization and template repo you can use so that lessons look consistent
- It's fine if you use some other static site generator or git-based lesson method.

Sphinx is a doc generator, not HTML generator.  It can:
- Markdown, Jupyter, and ReST (and more...) inputs.  (jupyter-book is Sphinx, so anything it can do we can do.  This was one of the inspirations for using Sphinx) 
- Good support for inline code.  Much more than static code display, if you want to look at extensions.
- generate different output formats (pdf, epub, etc)
- strong cross-referencing within and between projects

What are your thoughts on what should be included here?

**Comment by bast** [comment]
Strong points of Sphinx (with extensions):
- tabs: they are very important for us and allow us to customize in-place instead of copying everything and fragmenting lessons
- emphasize lines: they make it easier to spot what has changed in longer code snippets
- you can write Markdown (I know it's an extension and a flavor of ...) and we really like and use MyST parser

**Comment by samumantha** [comment]
Yes this was thought to be the second episode after lesson development :+1: 
After a bit of show and tell, this lesson could be a nice big exercise, with everyone creating their own first lesson from the template with some hints on the special and cool features that one can use? Maybe some hints on how to adapt it to own needs in end?
If you want to do that, please let me know what kind of stuff people should have installed, so we can inform them next week.

**Comment by rkdarst** [comment]
(moved from coordination issue):

Lesson template -> "Lessons with version control"
* Start with general discussion of "why use version control?"
  * Shareable
  * History
  * Others can contribute, fork, etc
* Lesson templates with git: discussion of options
  * Carpentries template
  * CodeRefinery template
  * Any static site generator
  * Your own normal documentation
* CodeRefinery lesson template
  * History: wanted to switch to something, someone suggested jupyter-book, we went one step back and used Sphinx
* Exercises: choose from the below, depending on your own interests:
  * Try out sphinx-lesson via our template: new lesson
  * Modify a sample lesson using git
  * Browse history of an old lesson.
  * Present your own format to your group, and to the course after the exercises.  Discuss what you like and don't like.

**Comment by rkdarst** [comment]
* Have some exercise that is "preparation to build lesson locally" that people can look at in advance if they want to do the local-build exercise.

**Comment by rkdarst** [comment]
What about a significant time for demo between the instructors: show a full cycle of cloning, preview, contribute?

**Comment by bast** [comment]
+1 I would as participant prefer to see a demo rather than being expected to do something on my own which I might be new to.

**Comment by samumantha** [comment]
What about the title of this episode, currently it is still in the materials as lesson template, should it also be adjusted to "lessons with version control" "version controlled lessons" or could it just be "Creating your own lessons"?

**Comment by bast** [comment]
I will rename lesson to "Lessons with version control" and close the issue?
